//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceType", Namespace="http://www.nemoq.se/")]
    public partial class ServiceType : object
    {
        
        private int IDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Priority", Namespace="http://www.nemoq.se/")]
    public partial class Priority : object
    {
        
        private int IDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cashier", Namespace="http://www.nemoq.se/")]
    public partial class Cashier : object
    {
        
        private int IDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.nemoq.se/", ConfigurationName="ServiceReference.NQWSZUSSoap")]
    public interface NQWSZUSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/GetServiceTypeList", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.GetServiceTypeListResponse> GetServiceTypeListAsync(ServiceReference.GetServiceTypeListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/GetServiceTypeListByCashier", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.GetServiceTypeListByCashierResponse> GetServiceTypeListByCashierAsync(ServiceReference.GetServiceTypeListByCashierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/GetPriorityList", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.GetPriorityListResponse> GetPriorityListAsync(ServiceReference.GetPriorityListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/GetPriorityListByCashier", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.GetPriorityListByCashierResponse> GetPriorityListByCashierAsync(ServiceReference.GetPriorityListByCashierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/SetPriority", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.SetPriorityResponse> SetPriorityAsync(ServiceReference.SetPriorityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/GetCashierList", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.GetCashierListResponse> GetCashierListAsync(ServiceReference.GetCashierListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/ActivateServiceType", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.ActivateServiceTypeResponse> ActivateServiceTypeAsync(ServiceReference.ActivateServiceTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/ActivateCashier", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.ActivateCashierResponse> ActivateCashierAsync(ServiceReference.ActivateCashierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/ActivateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.ActivateUserResponse> ActivateUserAsync(ServiceReference.ActivateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/AssignServiceType", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.AssignServiceTypeResponse> AssignServiceTypeAsync(ServiceReference.AssignServiceTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/UnssignServiceType", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.UnssignServiceTypeResponse> UnssignServiceTypeAsync(ServiceReference.UnssignServiceTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/IsServiceTypeStatusActive", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.IsServiceTypeStatusActiveResponse> IsServiceTypeStatusActiveAsync(ServiceReference.IsServiceTypeStatusActiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/IsCashierStatusActive", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.IsCashierStatusActiveResponse> IsCashierStatusActiveAsync(ServiceReference.IsCashierStatusActiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/IsUserStatusActive", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.IsUserStatusActiveResponse> IsUserStatusActiveAsync(ServiceReference.IsUserStatusActiveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceTypeListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceTypeList", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.GetServiceTypeListRequestBody Body;
        
        public GetServiceTypeListRequest()
        {
        }
        
        public GetServiceTypeListRequest(ServiceReference.GetServiceTypeListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetServiceTypeListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Port;
        
        public GetServiceTypeListRequestBody()
        {
        }
        
        public GetServiceTypeListRequestBody(string Host, int Port)
        {
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceTypeListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceTypeListResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.GetServiceTypeListResponseBody Body;
        
        public GetServiceTypeListResponse()
        {
        }
        
        public GetServiceTypeListResponse(ServiceReference.GetServiceTypeListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetServiceTypeListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.ServiceType[] GetServiceTypeListResult;
        
        public GetServiceTypeListResponseBody()
        {
        }
        
        public GetServiceTypeListResponseBody(ServiceReference.ServiceType[] GetServiceTypeListResult)
        {
            this.GetServiceTypeListResult = GetServiceTypeListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceTypeListByCashierRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceTypeListByCashier", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.GetServiceTypeListByCashierRequestBody Body;
        
        public GetServiceTypeListByCashierRequest()
        {
        }
        
        public GetServiceTypeListByCashierRequest(ServiceReference.GetServiceTypeListByCashierRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetServiceTypeListByCashierRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Cashier;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Port;
        
        public GetServiceTypeListByCashierRequestBody()
        {
        }
        
        public GetServiceTypeListByCashierRequestBody(int Cashier, string Host, int Port)
        {
            this.Cashier = Cashier;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceTypeListByCashierResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceTypeListByCashierResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.GetServiceTypeListByCashierResponseBody Body;
        
        public GetServiceTypeListByCashierResponse()
        {
        }
        
        public GetServiceTypeListByCashierResponse(ServiceReference.GetServiceTypeListByCashierResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetServiceTypeListByCashierResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.ServiceType[] GetServiceTypeListByCashierResult;
        
        public GetServiceTypeListByCashierResponseBody()
        {
        }
        
        public GetServiceTypeListByCashierResponseBody(ServiceReference.ServiceType[] GetServiceTypeListByCashierResult)
        {
            this.GetServiceTypeListByCashierResult = GetServiceTypeListByCashierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPriorityListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPriorityList", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.GetPriorityListRequestBody Body;
        
        public GetPriorityListRequest()
        {
        }
        
        public GetPriorityListRequest(ServiceReference.GetPriorityListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetPriorityListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Port;
        
        public GetPriorityListRequestBody()
        {
        }
        
        public GetPriorityListRequestBody(string Host, int Port)
        {
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPriorityListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPriorityListResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.GetPriorityListResponseBody Body;
        
        public GetPriorityListResponse()
        {
        }
        
        public GetPriorityListResponse(ServiceReference.GetPriorityListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetPriorityListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.Priority[] GetPriorityListResult;
        
        public GetPriorityListResponseBody()
        {
        }
        
        public GetPriorityListResponseBody(ServiceReference.Priority[] GetPriorityListResult)
        {
            this.GetPriorityListResult = GetPriorityListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPriorityListByCashierRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPriorityListByCashier", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.GetPriorityListByCashierRequestBody Body;
        
        public GetPriorityListByCashierRequest()
        {
        }
        
        public GetPriorityListByCashierRequest(ServiceReference.GetPriorityListByCashierRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetPriorityListByCashierRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Cashier;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Port;
        
        public GetPriorityListByCashierRequestBody()
        {
        }
        
        public GetPriorityListByCashierRequestBody(int Cashier, string Host, int Port)
        {
            this.Cashier = Cashier;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPriorityListByCashierResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPriorityListByCashierResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.GetPriorityListByCashierResponseBody Body;
        
        public GetPriorityListByCashierResponse()
        {
        }
        
        public GetPriorityListByCashierResponse(ServiceReference.GetPriorityListByCashierResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetPriorityListByCashierResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.Priority[] GetPriorityListByCashierResult;
        
        public GetPriorityListByCashierResponseBody()
        {
        }
        
        public GetPriorityListByCashierResponseBody(ServiceReference.Priority[] GetPriorityListByCashierResult)
        {
            this.GetPriorityListByCashierResult = GetPriorityListByCashierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPriorityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPriority", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.SetPriorityRequestBody Body;
        
        public SetPriorityRequest()
        {
        }
        
        public SetPriorityRequest(ServiceReference.SetPriorityRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class SetPriorityRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CashierNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int PriorityNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Port;
        
        public SetPriorityRequestBody()
        {
        }
        
        public SetPriorityRequestBody(int CashierNr, int PriorityNr, string Host, int Port)
        {
            this.CashierNr = CashierNr;
            this.PriorityNr = PriorityNr;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPriorityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPriorityResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.SetPriorityResponseBody Body;
        
        public SetPriorityResponse()
        {
        }
        
        public SetPriorityResponse(ServiceReference.SetPriorityResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class SetPriorityResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetPriorityResult;
        
        public SetPriorityResponseBody()
        {
        }
        
        public SetPriorityResponseBody(bool SetPriorityResult)
        {
            this.SetPriorityResult = SetPriorityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCashierListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCashierList", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.GetCashierListRequestBody Body;
        
        public GetCashierListRequest()
        {
        }
        
        public GetCashierListRequest(ServiceReference.GetCashierListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetCashierListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Port;
        
        public GetCashierListRequestBody()
        {
        }
        
        public GetCashierListRequestBody(string Host, int Port)
        {
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCashierListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCashierListResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.GetCashierListResponseBody Body;
        
        public GetCashierListResponse()
        {
        }
        
        public GetCashierListResponse(ServiceReference.GetCashierListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetCashierListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.Cashier[] GetCashierListResult;
        
        public GetCashierListResponseBody()
        {
        }
        
        public GetCashierListResponseBody(ServiceReference.Cashier[] GetCashierListResult)
        {
            this.GetCashierListResult = GetCashierListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivateServiceTypeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivateServiceType", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.ActivateServiceTypeRequestBody Body;
        
        public ActivateServiceTypeRequest()
        {
        }
        
        public ActivateServiceTypeRequest(ServiceReference.ActivateServiceTypeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class ActivateServiceTypeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ServiceTypeNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool Status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Port;
        
        public ActivateServiceTypeRequestBody()
        {
        }
        
        public ActivateServiceTypeRequestBody(int ServiceTypeNr, bool Status, string Host, int Port)
        {
            this.ServiceTypeNr = ServiceTypeNr;
            this.Status = Status;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivateServiceTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivateServiceTypeResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.ActivateServiceTypeResponseBody Body;
        
        public ActivateServiceTypeResponse()
        {
        }
        
        public ActivateServiceTypeResponse(ServiceReference.ActivateServiceTypeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class ActivateServiceTypeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActivateServiceTypeResult;
        
        public ActivateServiceTypeResponseBody()
        {
        }
        
        public ActivateServiceTypeResponseBody(bool ActivateServiceTypeResult)
        {
            this.ActivateServiceTypeResult = ActivateServiceTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivateCashierRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivateCashier", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.ActivateCashierRequestBody Body;
        
        public ActivateCashierRequest()
        {
        }
        
        public ActivateCashierRequest(ServiceReference.ActivateCashierRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class ActivateCashierRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CashierNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool Status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Port;
        
        public ActivateCashierRequestBody()
        {
        }
        
        public ActivateCashierRequestBody(int CashierNr, bool Status, string Host, int Port)
        {
            this.CashierNr = CashierNr;
            this.Status = Status;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivateCashierResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivateCashierResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.ActivateCashierResponseBody Body;
        
        public ActivateCashierResponse()
        {
        }
        
        public ActivateCashierResponse(ServiceReference.ActivateCashierResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class ActivateCashierResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActivateCashierResult;
        
        public ActivateCashierResponseBody()
        {
        }
        
        public ActivateCashierResponseBody(bool ActivateCashierResult)
        {
            this.ActivateCashierResult = ActivateCashierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivateUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivateUser", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.ActivateUserRequestBody Body;
        
        public ActivateUserRequest()
        {
        }
        
        public ActivateUserRequest(ServiceReference.ActivateUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class ActivateUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool Status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Port;
        
        public ActivateUserRequestBody()
        {
        }
        
        public ActivateUserRequestBody(int UserNr, bool Status, string Host, int Port)
        {
            this.UserNr = UserNr;
            this.Status = Status;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivateUserResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.ActivateUserResponseBody Body;
        
        public ActivateUserResponse()
        {
        }
        
        public ActivateUserResponse(ServiceReference.ActivateUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class ActivateUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActivateUserResult;
        
        public ActivateUserResponseBody()
        {
        }
        
        public ActivateUserResponseBody(bool ActivateUserResult)
        {
            this.ActivateUserResult = ActivateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AssignServiceTypeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AssignServiceType", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.AssignServiceTypeRequestBody Body;
        
        public AssignServiceTypeRequest()
        {
        }
        
        public AssignServiceTypeRequest(ServiceReference.AssignServiceTypeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class AssignServiceTypeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CashierNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ServiceType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Port;
        
        public AssignServiceTypeRequestBody()
        {
        }
        
        public AssignServiceTypeRequestBody(int CashierNr, int ServiceType, string Host, int Port)
        {
            this.CashierNr = CashierNr;
            this.ServiceType = ServiceType;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AssignServiceTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AssignServiceTypeResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.AssignServiceTypeResponseBody Body;
        
        public AssignServiceTypeResponse()
        {
        }
        
        public AssignServiceTypeResponse(ServiceReference.AssignServiceTypeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class AssignServiceTypeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AssignServiceTypeResult;
        
        public AssignServiceTypeResponseBody()
        {
        }
        
        public AssignServiceTypeResponseBody(bool AssignServiceTypeResult)
        {
            this.AssignServiceTypeResult = AssignServiceTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnssignServiceTypeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnssignServiceType", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.UnssignServiceTypeRequestBody Body;
        
        public UnssignServiceTypeRequest()
        {
        }
        
        public UnssignServiceTypeRequest(ServiceReference.UnssignServiceTypeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class UnssignServiceTypeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CashierNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ServiceType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Port;
        
        public UnssignServiceTypeRequestBody()
        {
        }
        
        public UnssignServiceTypeRequestBody(int CashierNr, int ServiceType, string Host, int Port)
        {
            this.CashierNr = CashierNr;
            this.ServiceType = ServiceType;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnssignServiceTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnssignServiceTypeResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.UnssignServiceTypeResponseBody Body;
        
        public UnssignServiceTypeResponse()
        {
        }
        
        public UnssignServiceTypeResponse(ServiceReference.UnssignServiceTypeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class UnssignServiceTypeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UnssignServiceTypeResult;
        
        public UnssignServiceTypeResponseBody()
        {
        }
        
        public UnssignServiceTypeResponseBody(bool UnssignServiceTypeResult)
        {
            this.UnssignServiceTypeResult = UnssignServiceTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsServiceTypeStatusActiveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsServiceTypeStatusActive", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.IsServiceTypeStatusActiveRequestBody Body;
        
        public IsServiceTypeStatusActiveRequest()
        {
        }
        
        public IsServiceTypeStatusActiveRequest(ServiceReference.IsServiceTypeStatusActiveRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class IsServiceTypeStatusActiveRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ServiceType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Port;
        
        public IsServiceTypeStatusActiveRequestBody()
        {
        }
        
        public IsServiceTypeStatusActiveRequestBody(int ServiceType, string Host, int Port)
        {
            this.ServiceType = ServiceType;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsServiceTypeStatusActiveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsServiceTypeStatusActiveResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.IsServiceTypeStatusActiveResponseBody Body;
        
        public IsServiceTypeStatusActiveResponse()
        {
        }
        
        public IsServiceTypeStatusActiveResponse(ServiceReference.IsServiceTypeStatusActiveResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class IsServiceTypeStatusActiveResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsServiceTypeStatusActiveResult;
        
        public IsServiceTypeStatusActiveResponseBody()
        {
        }
        
        public IsServiceTypeStatusActiveResponseBody(bool IsServiceTypeStatusActiveResult)
        {
            this.IsServiceTypeStatusActiveResult = IsServiceTypeStatusActiveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsCashierStatusActiveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsCashierStatusActive", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.IsCashierStatusActiveRequestBody Body;
        
        public IsCashierStatusActiveRequest()
        {
        }
        
        public IsCashierStatusActiveRequest(ServiceReference.IsCashierStatusActiveRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class IsCashierStatusActiveRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CashierNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Port;
        
        public IsCashierStatusActiveRequestBody()
        {
        }
        
        public IsCashierStatusActiveRequestBody(int CashierNr, string Host, int Port)
        {
            this.CashierNr = CashierNr;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsCashierStatusActiveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsCashierStatusActiveResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.IsCashierStatusActiveResponseBody Body;
        
        public IsCashierStatusActiveResponse()
        {
        }
        
        public IsCashierStatusActiveResponse(ServiceReference.IsCashierStatusActiveResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class IsCashierStatusActiveResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsCashierStatusActiveResult;
        
        public IsCashierStatusActiveResponseBody()
        {
        }
        
        public IsCashierStatusActiveResponseBody(bool IsCashierStatusActiveResult)
        {
            this.IsCashierStatusActiveResult = IsCashierStatusActiveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUserStatusActiveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUserStatusActive", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.IsUserStatusActiveRequestBody Body;
        
        public IsUserStatusActiveRequest()
        {
        }
        
        public IsUserStatusActiveRequest(ServiceReference.IsUserStatusActiveRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class IsUserStatusActiveRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Port;
        
        public IsUserStatusActiveRequestBody()
        {
        }
        
        public IsUserStatusActiveRequestBody(int UserNr, string Host, int Port)
        {
            this.UserNr = UserNr;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUserStatusActiveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUserStatusActiveResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public ServiceReference.IsUserStatusActiveResponseBody Body;
        
        public IsUserStatusActiveResponse()
        {
        }
        
        public IsUserStatusActiveResponse(ServiceReference.IsUserStatusActiveResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class IsUserStatusActiveResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsUserStatusActiveResult;
        
        public IsUserStatusActiveResponseBody()
        {
        }
        
        public IsUserStatusActiveResponseBody(bool IsUserStatusActiveResult)
        {
            this.IsUserStatusActiveResult = IsUserStatusActiveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface NQWSZUSSoapChannel : ServiceReference.NQWSZUSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class NQWSZUSSoapClient : System.ServiceModel.ClientBase<ServiceReference.NQWSZUSSoap>, ServiceReference.NQWSZUSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NQWSZUSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(NQWSZUSSoapClient.GetBindingForEndpoint(endpointConfiguration), NQWSZUSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NQWSZUSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NQWSZUSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NQWSZUSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NQWSZUSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NQWSZUSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetServiceTypeListResponse> ServiceReference.NQWSZUSSoap.GetServiceTypeListAsync(ServiceReference.GetServiceTypeListRequest request)
        {
            return base.Channel.GetServiceTypeListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetServiceTypeListResponse> GetServiceTypeListAsync(string Host, int Port)
        {
            ServiceReference.GetServiceTypeListRequest inValue = new ServiceReference.GetServiceTypeListRequest();
            inValue.Body = new ServiceReference.GetServiceTypeListRequestBody();
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((ServiceReference.NQWSZUSSoap)(this)).GetServiceTypeListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetServiceTypeListByCashierResponse> ServiceReference.NQWSZUSSoap.GetServiceTypeListByCashierAsync(ServiceReference.GetServiceTypeListByCashierRequest request)
        {
            return base.Channel.GetServiceTypeListByCashierAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetServiceTypeListByCashierResponse> GetServiceTypeListByCashierAsync(int Cashier, string Host, int Port)
        {
            ServiceReference.GetServiceTypeListByCashierRequest inValue = new ServiceReference.GetServiceTypeListByCashierRequest();
            inValue.Body = new ServiceReference.GetServiceTypeListByCashierRequestBody();
            inValue.Body.Cashier = Cashier;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((ServiceReference.NQWSZUSSoap)(this)).GetServiceTypeListByCashierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetPriorityListResponse> ServiceReference.NQWSZUSSoap.GetPriorityListAsync(ServiceReference.GetPriorityListRequest request)
        {
            return base.Channel.GetPriorityListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetPriorityListResponse> GetPriorityListAsync(string Host, int Port)
        {
            ServiceReference.GetPriorityListRequest inValue = new ServiceReference.GetPriorityListRequest();
            inValue.Body = new ServiceReference.GetPriorityListRequestBody();
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((ServiceReference.NQWSZUSSoap)(this)).GetPriorityListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetPriorityListByCashierResponse> ServiceReference.NQWSZUSSoap.GetPriorityListByCashierAsync(ServiceReference.GetPriorityListByCashierRequest request)
        {
            return base.Channel.GetPriorityListByCashierAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetPriorityListByCashierResponse> GetPriorityListByCashierAsync(int Cashier, string Host, int Port)
        {
            ServiceReference.GetPriorityListByCashierRequest inValue = new ServiceReference.GetPriorityListByCashierRequest();
            inValue.Body = new ServiceReference.GetPriorityListByCashierRequestBody();
            inValue.Body.Cashier = Cashier;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((ServiceReference.NQWSZUSSoap)(this)).GetPriorityListByCashierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.SetPriorityResponse> ServiceReference.NQWSZUSSoap.SetPriorityAsync(ServiceReference.SetPriorityRequest request)
        {
            return base.Channel.SetPriorityAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.SetPriorityResponse> SetPriorityAsync(int CashierNr, int PriorityNr, string Host, int Port)
        {
            ServiceReference.SetPriorityRequest inValue = new ServiceReference.SetPriorityRequest();
            inValue.Body = new ServiceReference.SetPriorityRequestBody();
            inValue.Body.CashierNr = CashierNr;
            inValue.Body.PriorityNr = PriorityNr;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((ServiceReference.NQWSZUSSoap)(this)).SetPriorityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.GetCashierListResponse> ServiceReference.NQWSZUSSoap.GetCashierListAsync(ServiceReference.GetCashierListRequest request)
        {
            return base.Channel.GetCashierListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.GetCashierListResponse> GetCashierListAsync(string Host, int Port)
        {
            ServiceReference.GetCashierListRequest inValue = new ServiceReference.GetCashierListRequest();
            inValue.Body = new ServiceReference.GetCashierListRequestBody();
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((ServiceReference.NQWSZUSSoap)(this)).GetCashierListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.ActivateServiceTypeResponse> ServiceReference.NQWSZUSSoap.ActivateServiceTypeAsync(ServiceReference.ActivateServiceTypeRequest request)
        {
            return base.Channel.ActivateServiceTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ActivateServiceTypeResponse> ActivateServiceTypeAsync(int ServiceTypeNr, bool Status, string Host, int Port)
        {
            ServiceReference.ActivateServiceTypeRequest inValue = new ServiceReference.ActivateServiceTypeRequest();
            inValue.Body = new ServiceReference.ActivateServiceTypeRequestBody();
            inValue.Body.ServiceTypeNr = ServiceTypeNr;
            inValue.Body.Status = Status;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((ServiceReference.NQWSZUSSoap)(this)).ActivateServiceTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.ActivateCashierResponse> ServiceReference.NQWSZUSSoap.ActivateCashierAsync(ServiceReference.ActivateCashierRequest request)
        {
            return base.Channel.ActivateCashierAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ActivateCashierResponse> ActivateCashierAsync(int CashierNr, bool Status, string Host, int Port)
        {
            ServiceReference.ActivateCashierRequest inValue = new ServiceReference.ActivateCashierRequest();
            inValue.Body = new ServiceReference.ActivateCashierRequestBody();
            inValue.Body.CashierNr = CashierNr;
            inValue.Body.Status = Status;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((ServiceReference.NQWSZUSSoap)(this)).ActivateCashierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.ActivateUserResponse> ServiceReference.NQWSZUSSoap.ActivateUserAsync(ServiceReference.ActivateUserRequest request)
        {
            return base.Channel.ActivateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.ActivateUserResponse> ActivateUserAsync(int UserNr, bool Status, string Host, int Port)
        {
            ServiceReference.ActivateUserRequest inValue = new ServiceReference.ActivateUserRequest();
            inValue.Body = new ServiceReference.ActivateUserRequestBody();
            inValue.Body.UserNr = UserNr;
            inValue.Body.Status = Status;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((ServiceReference.NQWSZUSSoap)(this)).ActivateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.AssignServiceTypeResponse> ServiceReference.NQWSZUSSoap.AssignServiceTypeAsync(ServiceReference.AssignServiceTypeRequest request)
        {
            return base.Channel.AssignServiceTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.AssignServiceTypeResponse> AssignServiceTypeAsync(int CashierNr, int ServiceType, string Host, int Port)
        {
            ServiceReference.AssignServiceTypeRequest inValue = new ServiceReference.AssignServiceTypeRequest();
            inValue.Body = new ServiceReference.AssignServiceTypeRequestBody();
            inValue.Body.CashierNr = CashierNr;
            inValue.Body.ServiceType = ServiceType;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((ServiceReference.NQWSZUSSoap)(this)).AssignServiceTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.UnssignServiceTypeResponse> ServiceReference.NQWSZUSSoap.UnssignServiceTypeAsync(ServiceReference.UnssignServiceTypeRequest request)
        {
            return base.Channel.UnssignServiceTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.UnssignServiceTypeResponse> UnssignServiceTypeAsync(int CashierNr, int ServiceType, string Host, int Port)
        {
            ServiceReference.UnssignServiceTypeRequest inValue = new ServiceReference.UnssignServiceTypeRequest();
            inValue.Body = new ServiceReference.UnssignServiceTypeRequestBody();
            inValue.Body.CashierNr = CashierNr;
            inValue.Body.ServiceType = ServiceType;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((ServiceReference.NQWSZUSSoap)(this)).UnssignServiceTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.IsServiceTypeStatusActiveResponse> ServiceReference.NQWSZUSSoap.IsServiceTypeStatusActiveAsync(ServiceReference.IsServiceTypeStatusActiveRequest request)
        {
            return base.Channel.IsServiceTypeStatusActiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.IsServiceTypeStatusActiveResponse> IsServiceTypeStatusActiveAsync(int ServiceType, string Host, int Port)
        {
            ServiceReference.IsServiceTypeStatusActiveRequest inValue = new ServiceReference.IsServiceTypeStatusActiveRequest();
            inValue.Body = new ServiceReference.IsServiceTypeStatusActiveRequestBody();
            inValue.Body.ServiceType = ServiceType;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((ServiceReference.NQWSZUSSoap)(this)).IsServiceTypeStatusActiveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.IsCashierStatusActiveResponse> ServiceReference.NQWSZUSSoap.IsCashierStatusActiveAsync(ServiceReference.IsCashierStatusActiveRequest request)
        {
            return base.Channel.IsCashierStatusActiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.IsCashierStatusActiveResponse> IsCashierStatusActiveAsync(int CashierNr, string Host, int Port)
        {
            ServiceReference.IsCashierStatusActiveRequest inValue = new ServiceReference.IsCashierStatusActiveRequest();
            inValue.Body = new ServiceReference.IsCashierStatusActiveRequestBody();
            inValue.Body.CashierNr = CashierNr;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((ServiceReference.NQWSZUSSoap)(this)).IsCashierStatusActiveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.IsUserStatusActiveResponse> ServiceReference.NQWSZUSSoap.IsUserStatusActiveAsync(ServiceReference.IsUserStatusActiveRequest request)
        {
            return base.Channel.IsUserStatusActiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.IsUserStatusActiveResponse> IsUserStatusActiveAsync(int UserNr, string Host, int Port)
        {
            ServiceReference.IsUserStatusActiveRequest inValue = new ServiceReference.IsUserStatusActiveRequest();
            inValue.Body = new ServiceReference.IsUserStatusActiveRequestBody();
            inValue.Body.UserNr = UserNr;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((ServiceReference.NQWSZUSSoap)(this)).IsUserStatusActiveAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NQWSZUSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.NQWSZUSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NQWSZUSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/NQC/NQWebServices/Wcf/NQWSZUS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.NQWSZUSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/NQC/NQWebServices/Wcf/NQWSZUS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            NQWSZUSSoap,
            
            NQWSZUSSoap12,
        }
    }
}
