//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nqwszus
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceType", Namespace="http://www.nemoq.se/")]
    public partial class ServiceType : object
    {
        
        private int IDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Priority", Namespace="http://www.nemoq.se/")]
    public partial class Priority : object
    {
        
        private int IDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cashier", Namespace="http://www.nemoq.se/")]
    public partial class Cashier : object
    {
        
        private int IDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.nemoq.se/", ConfigurationName="nqwszus.NQWSZUSSoap")]
    public interface NQWSZUSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/GetServiceTypeList", ReplyAction="*")]
        System.Threading.Tasks.Task<nqwszus.GetServiceTypeListResponse> GetServiceTypeListAsync(nqwszus.GetServiceTypeListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/GetServiceTypeListByCashier", ReplyAction="*")]
        System.Threading.Tasks.Task<nqwszus.GetServiceTypeListByCashierResponse> GetServiceTypeListByCashierAsync(nqwszus.GetServiceTypeListByCashierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/GetPriorityList", ReplyAction="*")]
        System.Threading.Tasks.Task<nqwszus.GetPriorityListResponse> GetPriorityListAsync(nqwszus.GetPriorityListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/GetPriorityListByCashier", ReplyAction="*")]
        System.Threading.Tasks.Task<nqwszus.GetPriorityListByCashierResponse> GetPriorityListByCashierAsync(nqwszus.GetPriorityListByCashierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/SetPriority", ReplyAction="*")]
        System.Threading.Tasks.Task<nqwszus.SetPriorityResponse> SetPriorityAsync(nqwszus.SetPriorityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/GetCashierList", ReplyAction="*")]
        System.Threading.Tasks.Task<nqwszus.GetCashierListResponse> GetCashierListAsync(nqwszus.GetCashierListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/ActivateServiceType", ReplyAction="*")]
        System.Threading.Tasks.Task<nqwszus.ActivateServiceTypeResponse> ActivateServiceTypeAsync(nqwszus.ActivateServiceTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/ActivateCashier", ReplyAction="*")]
        System.Threading.Tasks.Task<nqwszus.ActivateCashierResponse> ActivateCashierAsync(nqwszus.ActivateCashierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/ActivateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<nqwszus.ActivateUserResponse> ActivateUserAsync(nqwszus.ActivateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/AssignServiceType", ReplyAction="*")]
        System.Threading.Tasks.Task<nqwszus.AssignServiceTypeResponse> AssignServiceTypeAsync(nqwszus.AssignServiceTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/UnssignServiceType", ReplyAction="*")]
        System.Threading.Tasks.Task<nqwszus.UnssignServiceTypeResponse> UnssignServiceTypeAsync(nqwszus.UnssignServiceTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/IsServiceTypeStatusActive", ReplyAction="*")]
        System.Threading.Tasks.Task<nqwszus.IsServiceTypeStatusActiveResponse> IsServiceTypeStatusActiveAsync(nqwszus.IsServiceTypeStatusActiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/IsCashierStatusActive", ReplyAction="*")]
        System.Threading.Tasks.Task<nqwszus.IsCashierStatusActiveResponse> IsCashierStatusActiveAsync(nqwszus.IsCashierStatusActiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.nemoq.se/IsUserStatusActive", ReplyAction="*")]
        System.Threading.Tasks.Task<nqwszus.IsUserStatusActiveResponse> IsUserStatusActiveAsync(nqwszus.IsUserStatusActiveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceTypeListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceTypeList", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.GetServiceTypeListRequestBody Body;
        
        public GetServiceTypeListRequest()
        {
        }
        
        public GetServiceTypeListRequest(nqwszus.GetServiceTypeListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetServiceTypeListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Port;
        
        public GetServiceTypeListRequestBody()
        {
        }
        
        public GetServiceTypeListRequestBody(string Host, int Port)
        {
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceTypeListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceTypeListResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.GetServiceTypeListResponseBody Body;
        
        public GetServiceTypeListResponse()
        {
        }
        
        public GetServiceTypeListResponse(nqwszus.GetServiceTypeListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetServiceTypeListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public nqwszus.ServiceType[] GetServiceTypeListResult;
        
        public GetServiceTypeListResponseBody()
        {
        }
        
        public GetServiceTypeListResponseBody(nqwszus.ServiceType[] GetServiceTypeListResult)
        {
            this.GetServiceTypeListResult = GetServiceTypeListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceTypeListByCashierRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceTypeListByCashier", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.GetServiceTypeListByCashierRequestBody Body;
        
        public GetServiceTypeListByCashierRequest()
        {
        }
        
        public GetServiceTypeListByCashierRequest(nqwszus.GetServiceTypeListByCashierRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetServiceTypeListByCashierRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Cashier;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Port;
        
        public GetServiceTypeListByCashierRequestBody()
        {
        }
        
        public GetServiceTypeListByCashierRequestBody(int Cashier, string Host, int Port)
        {
            this.Cashier = Cashier;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceTypeListByCashierResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceTypeListByCashierResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.GetServiceTypeListByCashierResponseBody Body;
        
        public GetServiceTypeListByCashierResponse()
        {
        }
        
        public GetServiceTypeListByCashierResponse(nqwszus.GetServiceTypeListByCashierResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetServiceTypeListByCashierResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public nqwszus.ServiceType[] GetServiceTypeListByCashierResult;
        
        public GetServiceTypeListByCashierResponseBody()
        {
        }
        
        public GetServiceTypeListByCashierResponseBody(nqwszus.ServiceType[] GetServiceTypeListByCashierResult)
        {
            this.GetServiceTypeListByCashierResult = GetServiceTypeListByCashierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPriorityListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPriorityList", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.GetPriorityListRequestBody Body;
        
        public GetPriorityListRequest()
        {
        }
        
        public GetPriorityListRequest(nqwszus.GetPriorityListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetPriorityListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Port;
        
        public GetPriorityListRequestBody()
        {
        }
        
        public GetPriorityListRequestBody(string Host, int Port)
        {
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPriorityListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPriorityListResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.GetPriorityListResponseBody Body;
        
        public GetPriorityListResponse()
        {
        }
        
        public GetPriorityListResponse(nqwszus.GetPriorityListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetPriorityListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public nqwszus.Priority[] GetPriorityListResult;
        
        public GetPriorityListResponseBody()
        {
        }
        
        public GetPriorityListResponseBody(nqwszus.Priority[] GetPriorityListResult)
        {
            this.GetPriorityListResult = GetPriorityListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPriorityListByCashierRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPriorityListByCashier", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.GetPriorityListByCashierRequestBody Body;
        
        public GetPriorityListByCashierRequest()
        {
        }
        
        public GetPriorityListByCashierRequest(nqwszus.GetPriorityListByCashierRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetPriorityListByCashierRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Cashier;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Port;
        
        public GetPriorityListByCashierRequestBody()
        {
        }
        
        public GetPriorityListByCashierRequestBody(int Cashier, string Host, int Port)
        {
            this.Cashier = Cashier;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPriorityListByCashierResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPriorityListByCashierResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.GetPriorityListByCashierResponseBody Body;
        
        public GetPriorityListByCashierResponse()
        {
        }
        
        public GetPriorityListByCashierResponse(nqwszus.GetPriorityListByCashierResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetPriorityListByCashierResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public nqwszus.Priority[] GetPriorityListByCashierResult;
        
        public GetPriorityListByCashierResponseBody()
        {
        }
        
        public GetPriorityListByCashierResponseBody(nqwszus.Priority[] GetPriorityListByCashierResult)
        {
            this.GetPriorityListByCashierResult = GetPriorityListByCashierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPriorityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPriority", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.SetPriorityRequestBody Body;
        
        public SetPriorityRequest()
        {
        }
        
        public SetPriorityRequest(nqwszus.SetPriorityRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class SetPriorityRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CashierNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int PriorityNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Port;
        
        public SetPriorityRequestBody()
        {
        }
        
        public SetPriorityRequestBody(int CashierNr, int PriorityNr, string Host, int Port)
        {
            this.CashierNr = CashierNr;
            this.PriorityNr = PriorityNr;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetPriorityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetPriorityResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.SetPriorityResponseBody Body;
        
        public SetPriorityResponse()
        {
        }
        
        public SetPriorityResponse(nqwszus.SetPriorityResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class SetPriorityResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetPriorityResult;
        
        public SetPriorityResponseBody()
        {
        }
        
        public SetPriorityResponseBody(bool SetPriorityResult)
        {
            this.SetPriorityResult = SetPriorityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCashierListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCashierList", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.GetCashierListRequestBody Body;
        
        public GetCashierListRequest()
        {
        }
        
        public GetCashierListRequest(nqwszus.GetCashierListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetCashierListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Port;
        
        public GetCashierListRequestBody()
        {
        }
        
        public GetCashierListRequestBody(string Host, int Port)
        {
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCashierListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCashierListResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.GetCashierListResponseBody Body;
        
        public GetCashierListResponse()
        {
        }
        
        public GetCashierListResponse(nqwszus.GetCashierListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class GetCashierListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public nqwszus.Cashier[] GetCashierListResult;
        
        public GetCashierListResponseBody()
        {
        }
        
        public GetCashierListResponseBody(nqwszus.Cashier[] GetCashierListResult)
        {
            this.GetCashierListResult = GetCashierListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivateServiceTypeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivateServiceType", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.ActivateServiceTypeRequestBody Body;
        
        public ActivateServiceTypeRequest()
        {
        }
        
        public ActivateServiceTypeRequest(nqwszus.ActivateServiceTypeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class ActivateServiceTypeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ServiceTypeNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool Status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Port;
        
        public ActivateServiceTypeRequestBody()
        {
        }
        
        public ActivateServiceTypeRequestBody(int ServiceTypeNr, bool Status, string Host, int Port)
        {
            this.ServiceTypeNr = ServiceTypeNr;
            this.Status = Status;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivateServiceTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivateServiceTypeResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.ActivateServiceTypeResponseBody Body;
        
        public ActivateServiceTypeResponse()
        {
        }
        
        public ActivateServiceTypeResponse(nqwszus.ActivateServiceTypeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class ActivateServiceTypeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActivateServiceTypeResult;
        
        public ActivateServiceTypeResponseBody()
        {
        }
        
        public ActivateServiceTypeResponseBody(bool ActivateServiceTypeResult)
        {
            this.ActivateServiceTypeResult = ActivateServiceTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivateCashierRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivateCashier", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.ActivateCashierRequestBody Body;
        
        public ActivateCashierRequest()
        {
        }
        
        public ActivateCashierRequest(nqwszus.ActivateCashierRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class ActivateCashierRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CashierNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool Status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Port;
        
        public ActivateCashierRequestBody()
        {
        }
        
        public ActivateCashierRequestBody(int CashierNr, bool Status, string Host, int Port)
        {
            this.CashierNr = CashierNr;
            this.Status = Status;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivateCashierResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivateCashierResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.ActivateCashierResponseBody Body;
        
        public ActivateCashierResponse()
        {
        }
        
        public ActivateCashierResponse(nqwszus.ActivateCashierResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class ActivateCashierResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActivateCashierResult;
        
        public ActivateCashierResponseBody()
        {
        }
        
        public ActivateCashierResponseBody(bool ActivateCashierResult)
        {
            this.ActivateCashierResult = ActivateCashierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivateUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivateUser", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.ActivateUserRequestBody Body;
        
        public ActivateUserRequest()
        {
        }
        
        public ActivateUserRequest(nqwszus.ActivateUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class ActivateUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool Status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Port;
        
        public ActivateUserRequestBody()
        {
        }
        
        public ActivateUserRequestBody(int UserNr, bool Status, string Host, int Port)
        {
            this.UserNr = UserNr;
            this.Status = Status;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivateUserResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.ActivateUserResponseBody Body;
        
        public ActivateUserResponse()
        {
        }
        
        public ActivateUserResponse(nqwszus.ActivateUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class ActivateUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActivateUserResult;
        
        public ActivateUserResponseBody()
        {
        }
        
        public ActivateUserResponseBody(bool ActivateUserResult)
        {
            this.ActivateUserResult = ActivateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AssignServiceTypeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AssignServiceType", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.AssignServiceTypeRequestBody Body;
        
        public AssignServiceTypeRequest()
        {
        }
        
        public AssignServiceTypeRequest(nqwszus.AssignServiceTypeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class AssignServiceTypeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CashierNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ServiceType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Port;
        
        public AssignServiceTypeRequestBody()
        {
        }
        
        public AssignServiceTypeRequestBody(int CashierNr, int ServiceType, string Host, int Port)
        {
            this.CashierNr = CashierNr;
            this.ServiceType = ServiceType;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AssignServiceTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AssignServiceTypeResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.AssignServiceTypeResponseBody Body;
        
        public AssignServiceTypeResponse()
        {
        }
        
        public AssignServiceTypeResponse(nqwszus.AssignServiceTypeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class AssignServiceTypeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AssignServiceTypeResult;
        
        public AssignServiceTypeResponseBody()
        {
        }
        
        public AssignServiceTypeResponseBody(bool AssignServiceTypeResult)
        {
            this.AssignServiceTypeResult = AssignServiceTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnssignServiceTypeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnssignServiceType", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.UnssignServiceTypeRequestBody Body;
        
        public UnssignServiceTypeRequest()
        {
        }
        
        public UnssignServiceTypeRequest(nqwszus.UnssignServiceTypeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class UnssignServiceTypeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CashierNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ServiceType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Port;
        
        public UnssignServiceTypeRequestBody()
        {
        }
        
        public UnssignServiceTypeRequestBody(int CashierNr, int ServiceType, string Host, int Port)
        {
            this.CashierNr = CashierNr;
            this.ServiceType = ServiceType;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnssignServiceTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnssignServiceTypeResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.UnssignServiceTypeResponseBody Body;
        
        public UnssignServiceTypeResponse()
        {
        }
        
        public UnssignServiceTypeResponse(nqwszus.UnssignServiceTypeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class UnssignServiceTypeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UnssignServiceTypeResult;
        
        public UnssignServiceTypeResponseBody()
        {
        }
        
        public UnssignServiceTypeResponseBody(bool UnssignServiceTypeResult)
        {
            this.UnssignServiceTypeResult = UnssignServiceTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsServiceTypeStatusActiveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsServiceTypeStatusActive", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.IsServiceTypeStatusActiveRequestBody Body;
        
        public IsServiceTypeStatusActiveRequest()
        {
        }
        
        public IsServiceTypeStatusActiveRequest(nqwszus.IsServiceTypeStatusActiveRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class IsServiceTypeStatusActiveRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ServiceType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Port;
        
        public IsServiceTypeStatusActiveRequestBody()
        {
        }
        
        public IsServiceTypeStatusActiveRequestBody(int ServiceType, string Host, int Port)
        {
            this.ServiceType = ServiceType;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsServiceTypeStatusActiveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsServiceTypeStatusActiveResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.IsServiceTypeStatusActiveResponseBody Body;
        
        public IsServiceTypeStatusActiveResponse()
        {
        }
        
        public IsServiceTypeStatusActiveResponse(nqwszus.IsServiceTypeStatusActiveResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class IsServiceTypeStatusActiveResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsServiceTypeStatusActiveResult;
        
        public IsServiceTypeStatusActiveResponseBody()
        {
        }
        
        public IsServiceTypeStatusActiveResponseBody(bool IsServiceTypeStatusActiveResult)
        {
            this.IsServiceTypeStatusActiveResult = IsServiceTypeStatusActiveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsCashierStatusActiveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsCashierStatusActive", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.IsCashierStatusActiveRequestBody Body;
        
        public IsCashierStatusActiveRequest()
        {
        }
        
        public IsCashierStatusActiveRequest(nqwszus.IsCashierStatusActiveRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class IsCashierStatusActiveRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CashierNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Port;
        
        public IsCashierStatusActiveRequestBody()
        {
        }
        
        public IsCashierStatusActiveRequestBody(int CashierNr, string Host, int Port)
        {
            this.CashierNr = CashierNr;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsCashierStatusActiveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsCashierStatusActiveResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.IsCashierStatusActiveResponseBody Body;
        
        public IsCashierStatusActiveResponse()
        {
        }
        
        public IsCashierStatusActiveResponse(nqwszus.IsCashierStatusActiveResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class IsCashierStatusActiveResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsCashierStatusActiveResult;
        
        public IsCashierStatusActiveResponseBody()
        {
        }
        
        public IsCashierStatusActiveResponseBody(bool IsCashierStatusActiveResult)
        {
            this.IsCashierStatusActiveResult = IsCashierStatusActiveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUserStatusActiveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUserStatusActive", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.IsUserStatusActiveRequestBody Body;
        
        public IsUserStatusActiveRequest()
        {
        }
        
        public IsUserStatusActiveRequest(nqwszus.IsUserStatusActiveRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class IsUserStatusActiveRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserNr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Host;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Port;
        
        public IsUserStatusActiveRequestBody()
        {
        }
        
        public IsUserStatusActiveRequestBody(int UserNr, string Host, int Port)
        {
            this.UserNr = UserNr;
            this.Host = Host;
            this.Port = Port;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUserStatusActiveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUserStatusActiveResponse", Namespace="http://www.nemoq.se/", Order=0)]
        public nqwszus.IsUserStatusActiveResponseBody Body;
        
        public IsUserStatusActiveResponse()
        {
        }
        
        public IsUserStatusActiveResponse(nqwszus.IsUserStatusActiveResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.nemoq.se/")]
    public partial class IsUserStatusActiveResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsUserStatusActiveResult;
        
        public IsUserStatusActiveResponseBody()
        {
        }
        
        public IsUserStatusActiveResponseBody(bool IsUserStatusActiveResult)
        {
            this.IsUserStatusActiveResult = IsUserStatusActiveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface NQWSZUSSoapChannel : nqwszus.NQWSZUSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class NQWSZUSSoapClient : System.ServiceModel.ClientBase<nqwszus.NQWSZUSSoap>, nqwszus.NQWSZUSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NQWSZUSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(NQWSZUSSoapClient.GetBindingForEndpoint(endpointConfiguration), NQWSZUSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NQWSZUSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NQWSZUSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NQWSZUSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NQWSZUSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NQWSZUSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nqwszus.GetServiceTypeListResponse> nqwszus.NQWSZUSSoap.GetServiceTypeListAsync(nqwszus.GetServiceTypeListRequest request)
        {
            return base.Channel.GetServiceTypeListAsync(request);
        }
        
        public System.Threading.Tasks.Task<nqwszus.GetServiceTypeListResponse> GetServiceTypeListAsync(string Host, int Port)
        {
            nqwszus.GetServiceTypeListRequest inValue = new nqwszus.GetServiceTypeListRequest();
            inValue.Body = new nqwszus.GetServiceTypeListRequestBody();
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((nqwszus.NQWSZUSSoap)(this)).GetServiceTypeListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nqwszus.GetServiceTypeListByCashierResponse> nqwszus.NQWSZUSSoap.GetServiceTypeListByCashierAsync(nqwszus.GetServiceTypeListByCashierRequest request)
        {
            return base.Channel.GetServiceTypeListByCashierAsync(request);
        }
        
        public System.Threading.Tasks.Task<nqwszus.GetServiceTypeListByCashierResponse> GetServiceTypeListByCashierAsync(int Cashier, string Host, int Port)
        {
            nqwszus.GetServiceTypeListByCashierRequest inValue = new nqwszus.GetServiceTypeListByCashierRequest();
            inValue.Body = new nqwszus.GetServiceTypeListByCashierRequestBody();
            inValue.Body.Cashier = Cashier;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((nqwszus.NQWSZUSSoap)(this)).GetServiceTypeListByCashierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nqwszus.GetPriorityListResponse> nqwszus.NQWSZUSSoap.GetPriorityListAsync(nqwszus.GetPriorityListRequest request)
        {
            return base.Channel.GetPriorityListAsync(request);
        }
        
        public System.Threading.Tasks.Task<nqwszus.GetPriorityListResponse> GetPriorityListAsync(string Host, int Port)
        {
            nqwszus.GetPriorityListRequest inValue = new nqwszus.GetPriorityListRequest();
            inValue.Body = new nqwszus.GetPriorityListRequestBody();
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((nqwszus.NQWSZUSSoap)(this)).GetPriorityListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nqwszus.GetPriorityListByCashierResponse> nqwszus.NQWSZUSSoap.GetPriorityListByCashierAsync(nqwszus.GetPriorityListByCashierRequest request)
        {
            return base.Channel.GetPriorityListByCashierAsync(request);
        }
        
        public System.Threading.Tasks.Task<nqwszus.GetPriorityListByCashierResponse> GetPriorityListByCashierAsync(int Cashier, string Host, int Port)
        {
            nqwszus.GetPriorityListByCashierRequest inValue = new nqwszus.GetPriorityListByCashierRequest();
            inValue.Body = new nqwszus.GetPriorityListByCashierRequestBody();
            inValue.Body.Cashier = Cashier;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((nqwszus.NQWSZUSSoap)(this)).GetPriorityListByCashierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nqwszus.SetPriorityResponse> nqwszus.NQWSZUSSoap.SetPriorityAsync(nqwszus.SetPriorityRequest request)
        {
            return base.Channel.SetPriorityAsync(request);
        }
        
        public System.Threading.Tasks.Task<nqwszus.SetPriorityResponse> SetPriorityAsync(int CashierNr, int PriorityNr, string Host, int Port)
        {
            nqwszus.SetPriorityRequest inValue = new nqwszus.SetPriorityRequest();
            inValue.Body = new nqwszus.SetPriorityRequestBody();
            inValue.Body.CashierNr = CashierNr;
            inValue.Body.PriorityNr = PriorityNr;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((nqwszus.NQWSZUSSoap)(this)).SetPriorityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nqwszus.GetCashierListResponse> nqwszus.NQWSZUSSoap.GetCashierListAsync(nqwszus.GetCashierListRequest request)
        {
            return base.Channel.GetCashierListAsync(request);
        }
        
        public System.Threading.Tasks.Task<nqwszus.GetCashierListResponse> GetCashierListAsync(string Host, int Port)
        {
            nqwszus.GetCashierListRequest inValue = new nqwszus.GetCashierListRequest();
            inValue.Body = new nqwszus.GetCashierListRequestBody();
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((nqwszus.NQWSZUSSoap)(this)).GetCashierListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nqwszus.ActivateServiceTypeResponse> nqwszus.NQWSZUSSoap.ActivateServiceTypeAsync(nqwszus.ActivateServiceTypeRequest request)
        {
            return base.Channel.ActivateServiceTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<nqwszus.ActivateServiceTypeResponse> ActivateServiceTypeAsync(int ServiceTypeNr, bool Status, string Host, int Port)
        {
            nqwszus.ActivateServiceTypeRequest inValue = new nqwszus.ActivateServiceTypeRequest();
            inValue.Body = new nqwszus.ActivateServiceTypeRequestBody();
            inValue.Body.ServiceTypeNr = ServiceTypeNr;
            inValue.Body.Status = Status;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((nqwszus.NQWSZUSSoap)(this)).ActivateServiceTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nqwszus.ActivateCashierResponse> nqwszus.NQWSZUSSoap.ActivateCashierAsync(nqwszus.ActivateCashierRequest request)
        {
            return base.Channel.ActivateCashierAsync(request);
        }
        
        public System.Threading.Tasks.Task<nqwszus.ActivateCashierResponse> ActivateCashierAsync(int CashierNr, bool Status, string Host, int Port)
        {
            nqwszus.ActivateCashierRequest inValue = new nqwszus.ActivateCashierRequest();
            inValue.Body = new nqwszus.ActivateCashierRequestBody();
            inValue.Body.CashierNr = CashierNr;
            inValue.Body.Status = Status;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((nqwszus.NQWSZUSSoap)(this)).ActivateCashierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nqwszus.ActivateUserResponse> nqwszus.NQWSZUSSoap.ActivateUserAsync(nqwszus.ActivateUserRequest request)
        {
            return base.Channel.ActivateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<nqwszus.ActivateUserResponse> ActivateUserAsync(int UserNr, bool Status, string Host, int Port)
        {
            nqwszus.ActivateUserRequest inValue = new nqwszus.ActivateUserRequest();
            inValue.Body = new nqwszus.ActivateUserRequestBody();
            inValue.Body.UserNr = UserNr;
            inValue.Body.Status = Status;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((nqwszus.NQWSZUSSoap)(this)).ActivateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nqwszus.AssignServiceTypeResponse> nqwszus.NQWSZUSSoap.AssignServiceTypeAsync(nqwszus.AssignServiceTypeRequest request)
        {
            return base.Channel.AssignServiceTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<nqwszus.AssignServiceTypeResponse> AssignServiceTypeAsync(int CashierNr, int ServiceType, string Host, int Port)
        {
            nqwszus.AssignServiceTypeRequest inValue = new nqwszus.AssignServiceTypeRequest();
            inValue.Body = new nqwszus.AssignServiceTypeRequestBody();
            inValue.Body.CashierNr = CashierNr;
            inValue.Body.ServiceType = ServiceType;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((nqwszus.NQWSZUSSoap)(this)).AssignServiceTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nqwszus.UnssignServiceTypeResponse> nqwszus.NQWSZUSSoap.UnssignServiceTypeAsync(nqwszus.UnssignServiceTypeRequest request)
        {
            return base.Channel.UnssignServiceTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<nqwszus.UnssignServiceTypeResponse> UnssignServiceTypeAsync(int CashierNr, int ServiceType, string Host, int Port)
        {
            nqwszus.UnssignServiceTypeRequest inValue = new nqwszus.UnssignServiceTypeRequest();
            inValue.Body = new nqwszus.UnssignServiceTypeRequestBody();
            inValue.Body.CashierNr = CashierNr;
            inValue.Body.ServiceType = ServiceType;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((nqwszus.NQWSZUSSoap)(this)).UnssignServiceTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nqwszus.IsServiceTypeStatusActiveResponse> nqwszus.NQWSZUSSoap.IsServiceTypeStatusActiveAsync(nqwszus.IsServiceTypeStatusActiveRequest request)
        {
            return base.Channel.IsServiceTypeStatusActiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<nqwszus.IsServiceTypeStatusActiveResponse> IsServiceTypeStatusActiveAsync(int ServiceType, string Host, int Port)
        {
            nqwszus.IsServiceTypeStatusActiveRequest inValue = new nqwszus.IsServiceTypeStatusActiveRequest();
            inValue.Body = new nqwszus.IsServiceTypeStatusActiveRequestBody();
            inValue.Body.ServiceType = ServiceType;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((nqwszus.NQWSZUSSoap)(this)).IsServiceTypeStatusActiveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nqwszus.IsCashierStatusActiveResponse> nqwszus.NQWSZUSSoap.IsCashierStatusActiveAsync(nqwszus.IsCashierStatusActiveRequest request)
        {
            return base.Channel.IsCashierStatusActiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<nqwszus.IsCashierStatusActiveResponse> IsCashierStatusActiveAsync(int CashierNr, string Host, int Port)
        {
            nqwszus.IsCashierStatusActiveRequest inValue = new nqwszus.IsCashierStatusActiveRequest();
            inValue.Body = new nqwszus.IsCashierStatusActiveRequestBody();
            inValue.Body.CashierNr = CashierNr;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((nqwszus.NQWSZUSSoap)(this)).IsCashierStatusActiveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nqwszus.IsUserStatusActiveResponse> nqwszus.NQWSZUSSoap.IsUserStatusActiveAsync(nqwszus.IsUserStatusActiveRequest request)
        {
            return base.Channel.IsUserStatusActiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<nqwszus.IsUserStatusActiveResponse> IsUserStatusActiveAsync(int UserNr, string Host, int Port)
        {
            nqwszus.IsUserStatusActiveRequest inValue = new nqwszus.IsUserStatusActiveRequest();
            inValue.Body = new nqwszus.IsUserStatusActiveRequestBody();
            inValue.Body.UserNr = UserNr;
            inValue.Body.Host = Host;
            inValue.Body.Port = Port;
            return ((nqwszus.NQWSZUSSoap)(this)).IsUserStatusActiveAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NQWSZUSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.NQWSZUSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NQWSZUSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/NQC/NQWebServices/Wcf/NQWSZUS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.NQWSZUSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/NQC/NQWebServices/Wcf/NQWSZUS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            NQWSZUSSoap,
            
            NQWSZUSSoap12,
        }
    }
}
